// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh86XG6ZEtc4Xf10xvcUn_wqGFdxMx-Hc',
    appId: '1:205354591702:web:86c327b4025485e356b077',
    messagingSenderId: '205354591702',
    projectId: 'complete-ecommerce-firebase23',
    authDomain: 'complete-ecommerce-firebase23.firebaseapp.com',
    storageBucket: 'complete-ecommerce-firebase23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXIkiexrAqVYlm_rLJqLRq0PKPIVA-rQ8',
    appId: '1:205354591702:android:d52367d88ad118dd56b077',
    messagingSenderId: '205354591702',
    projectId: 'complete-ecommerce-firebase23',
    storageBucket: 'complete-ecommerce-firebase23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmubJ3jm7_366REIW_hrW9QomGrAxk0yw',
    appId: '1:205354591702:ios:17577e0a6d18cf7656b077',
    messagingSenderId: '205354591702',
    projectId: 'complete-ecommerce-firebase23',
    storageBucket: 'complete-ecommerce-firebase23.appspot.com',
    iosBundleId: 'com.example.completeEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmubJ3jm7_366REIW_hrW9QomGrAxk0yw',
    appId: '1:205354591702:ios:2ef1949bc66f938a56b077',
    messagingSenderId: '205354591702',
    projectId: 'complete-ecommerce-firebase23',
    storageBucket: 'complete-ecommerce-firebase23.appspot.com',
    iosBundleId: 'com.example.completeEcommerce.RunnerTests',
  );
}
